services:
  api:
    build: .
    command: uvicorn api:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    volumes:
      - ./models:/app/models

  streamlit:
    build: .
    ports:
      - "8501:8501"
    volumes:
      - ./models:/app/models
